03/09/2025 14:33:32 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03/09/2025 14:33:32 - INFO - [33mPress CTRL+C to quit[0m
03/09/2025 14:33:32 - INFO -  * Restarting with stat
03/09/2025 14:33:33 - WARNING -  * Debugger is active!
03/09/2025 14:33:33 - INFO -  * Debugger PIN: 528-364-890
03/09/2025 14:33:45 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03/09/2025 14:33:45 - INFO - [33mPress CTRL+C to quit[0m
03/09/2025 14:34:00 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:00] "GET / HTTP/1.1" 200 -
03/09/2025 14:34:12 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03/09/2025 14:34:12 - INFO - [33mPress CTRL+C to quit[0m
03/09/2025 14:34:15 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:15] "GET / HTTP/1.1" 200 -
03/09/2025 14:34:17 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:17] "GET / HTTP/1.1" 200 -
03/09/2025 14:34:20 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:20] "GET /logs HTTP/1.1" 200 -
03/09/2025 14:34:37 - INFO - Usu√°rio 'admin' fez logout.
03/09/2025 14:34:37 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:37] "[32mGET /logout HTTP/1.1[0m" 302 -
03/09/2025 14:34:37 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:37] "GET /login HTTP/1.1" 200 -
03/09/2025 14:34:38 - INFO - Usu√°rio 'admin' fez login.
03/09/2025 14:34:38 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:38] "[32mPOST /login HTTP/1.1[0m" 302 -
03/09/2025 14:34:38 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:38] "GET / HTTP/1.1" 200 -
03/09/2025 14:34:40 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:40] "GET /relatorio HTTP/1.1" 200 -
03/09/2025 14:34:42 - INFO - 127.0.0.1 - - [03/Sep/2025 14:34:42] "GET /logs HTTP/1.1" 200 -
03/09/2025 14:36:06 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:11 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:13 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:13 - ERROR - Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 59, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 104, in view_logs
    return render_template('logs.html', log_entries=log_entries)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\logs.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:13 - ERROR - Exception on /logs [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 59, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 104, in view_logs
    return render_template('logs.html', log_entries=log_entries)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\logs.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:36:27 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 49, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 112, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 154, in top-level template code
    <a href="{{ url_for('relatorio') }}" class="{{ 'active' if request.path == '/relatorio' else '' }}">Relat√≥rio</a>
    ^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'relatorio'. Did you mean 'login' instead?
03/09/2025 14:38:34 - INFO - Usu√°rio 'admin' fez logout.
03/09/2025 14:38:35 - INFO - Usu√°rio 'admin' fez login.
03/09/2025 14:52:41 - INFO - Usu√°rio 'admin' fez logout.
03/09/2025 14:52:45 - INFO - Usu√°rio 'visitante' fez login.
03/09/2025 14:52:48 - INFO - Usu√°rio 'visitante' fez logout.
03/09/2025 15:02:31 - INFO - Usu√°rio 'admin' fez login.
03/09/2025 15:09:21 - INFO - Usu√°rio 'admin' fez logout.
03/09/2025 15:09:24 - INFO - Usu√°rio 'visitante' fez login.
03/09/2025 15:19:40 - INFO - Usu√°rio 'visitante' fez logout.
03/09/2025 15:19:42 - INFO - Usu√°rio 'admin' fez login.
03/09/2025 15:24:23 - INFO - Admin 'admin' CRIOU o usu√°rio 'Victor' com a permiss√£o 'admin'.
03/09/2025 15:24:26 - INFO - Usu√°rio 'admin' fez logout.
03/09/2025 15:24:29 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 15:24:38 - INFO - Admin 'Victor' CRIOU o usu√°rio 'Teste' com a permiss√£o 'viewer'.
03/09/2025 15:24:39 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 15:24:41 - INFO - Usu√°rio 'Teste' fez login.
03/09/2025 15:24:44 - INFO - Usu√°rio 'Teste' fez logout.
03/09/2025 15:24:46 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 15:45:39 - INFO - Admin 'Victor' ALTEROU a permiss√£o de 'visitante' para 'viewer'.
03/09/2025 15:46:06 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 15:46:07 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 15:46:26 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 15:46:29 - WARNING - Tentativa de login falhou para o usu√°rio 'Visitante'.
03/09/2025 15:46:35 - INFO - Usu√°rio 'visitante' fez login.
03/09/2025 15:46:39 - INFO - Usu√°rio 'visitante' fez logout.
03/09/2025 15:46:42 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 15:53:56 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 15:53:59 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 16:05:15 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 16:05:17 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 16:12:45 - INFO - Usu√°rio 'Victor' EXPORTOU os dados para PDF.
03/09/2025 16:15:37 - INFO - Usu√°rio 'Victor' EXPORTOU os dados para PDF.
03/09/2025 16:16:46 - INFO - Usu√°rio 'Victor' EXPORTOU os dados para PDF.
03/09/2025 16:42:56 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 16:42:58 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 16:43:45 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 16:44:17 - INFO - Usu√°rio 'Victor' fez login.
03/09/2025 17:40:07 - INFO - Admin 'Victor' CRIOU o usu√°rio 'Leandro' com a permiss√£o 'admin'.
03/09/2025 17:40:21 - INFO - Admin 'Victor' CRIOU o usu√°rio 'Caio' com a permiss√£o 'admin'.
03/09/2025 17:40:33 - INFO - Admin 'Victor' CRIOU o usu√°rio 'Ari' com a permiss√£o 'admin'.
03/09/2025 17:40:45 - INFO - Admin 'Victor' CRIOU o usu√°rio 'Luciano' com a permiss√£o 'admin'.
03/09/2025 17:40:54 - INFO - Admin 'Victor' CRIOU o usu√°rio 'Matheus' com a permiss√£o 'admin'.
03/09/2025 17:41:28 - INFO - Admin 'Victor' DELETOU o usu√°rio 'Ari'.
03/09/2025 17:47:51 - INFO - Usu√°rio 'Victor' fez logout.
03/09/2025 17:47:57 - INFO - Usu√°rio 'visitante' fez login.
03/09/2025 17:55:01 - INFO - Usu√°rio 'visitante' fez logout.
03/09/2025 17:55:09 - INFO - Usu√°rio 'admin' fez login.
03/09/2025 18:02:31 - INFO - Usu√°rio 'admin' fez logout.
03/09/2025 18:02:35 - WARNING - Tentativa de login falhou para o usu√°rio 'Kleber'.
03/09/2025 18:02:36 - INFO - Usu√°rio 'admin' fez login.
04/09/2025 09:58:38 - INFO - Usu√°rio 'admin' DELETOU o aluno 'Victor'.
04/09/2025 09:58:52 - INFO - Admin 'admin' DELETOU o usu√°rio 'Leandro'.
04/09/2025 09:58:55 - INFO - Admin 'admin' DELETOU o usu√°rio 'Caio'.
04/09/2025 09:58:58 - INFO - Admin 'admin' DELETOU o usu√°rio 'Luciano'.
04/09/2025 09:59:00 - INFO - Admin 'admin' DELETOU o usu√°rio 'Matheus'.
04/09/2025 09:59:11 - INFO - Usu√°rio 'admin' ADICIONOU o aluno 'Victor'.
04/09/2025 09:59:14 - INFO - Usu√°rio 'admin' fez logout.
04/09/2025 09:59:18 - INFO - Usu√°rio 'Victor' fez login.
04/09/2025 10:12:18 - INFO - Usu√°rio 'Victor' fez logout.
04/09/2025 10:12:23 - INFO - Usu√°rio 'visitante' fez login.
04/09/2025 10:12:40 - INFO - Usu√°rio 'visitante' fez logout.
04/09/2025 10:12:43 - INFO - Usu√°rio 'Victor' fez login.
04/09/2025 11:06:09 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 90, in index
    return render_template('index.html', chart_data=chart_data)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:06:11 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 90, in index
    return render_template('index.html', chart_data=chart_data)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:06:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 90, in index
    return render_template('index.html', chart_data=chart_data)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:06:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 90, in index
    return render_template('index.html', chart_data=chart_data)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:06:12 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 90, in index
    return render_template('index.html', chart_data=chart_data)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:06:20 - ERROR - Exception on /adicionar [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 47, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 144, in adicionar
    return render_template('adicionar.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\adicionar.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:06:29 - INFO - Usu√°rio 'Victor' fez login.
04/09/2025 11:06:29 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 90, in index
    return render_template('index.html', chart_data=chart_data)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 17, in top-level template code
    <a href="{{ url_for('meu_perfil') }}" title="Meu Perfil" class="nav-user-link">
    ^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'meu_perfil'. Did you mean 'exportar' instead?
04/09/2025 11:19:14 - INFO - Usu√°rio 'Victor' ADICIONOU o aluno 'Teste'.
04/09/2025 11:19:28 - INFO - Usu√°rio 'Victor' DELETOU o aluno 'Victor'.
04/09/2025 11:19:37 - INFO - Usu√°rio 'Victor' ADICIONOU o aluno 'Caralho'.
04/09/2025 11:19:50 - INFO - Usu√°rio 'Victor' DELETOU o aluno 'Caralho'.
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 33, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 78, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 33, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 78, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 33, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 78, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 33, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 78, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on /lista [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 33, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 92, in lista_alunos
    return render_template('lista_alunos.html', alunos=alunos)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\lista_alunos.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\lista_alunos.html", line 30, in block 'content'
    <a href="{{ url_for('editar', nome_do_aluno=aluno.nome) }}" class="action-btn edit-btn">Editar</a>
    ^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'editar' with values ['nome_do_aluno']. Did you mean 'editar_aluno' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 35, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 81, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 35, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 81, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 35, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 81, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 35, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 81, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 35, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 81, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 34, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 79, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\app.py", line 34, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Corsini\Desktop\teste\app.py", line 79, in index
    return render_template('index.html')
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Corsini\Desktop\teste\templates\base.html", line 61, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\Desktop\teste\templates\index.html", line 116, in block 'content'
    <a href="{{ url_for('adicionar') }}" class="action-card">
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Corsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'adicionar'. Did you mean 'static' instead?
Admin 'Victor' ADICIONOU o aluno 'Victor'.
Admin 'Victor' CRIOU a conta de login para 'Victor'.
Admin 'Victor' ADICIONOU o aluno 'Teste'.
Admin 'Victor' DELETOU o aluno 'Teste'.
Admin 'Victor' DELETOU o usu√°rio associado a 'Teste'.
Admin 'Victor' ADICIONOU o aluno 'Victor'.
Admin 'Victor' CRIOU a conta de login para 'Victor'.
Admin 'Victor' ADICIONOU o aluno 'Kleber'.
Admin 'Victor' CRIOU a conta de login para 'Kleber'.
Usu√°rio 'Victor' EXPORTOU os dados para PDF.
Admin 'Victor' ADICIONOU o aluno 'Astolfo'.
Admin 'Victor' CRIOU a conta de login para 'Astolfo'.
Usu√°rio 'Victor' fez logout.
Tentativa de login falhou para o usu√°rio 'Altolfo'.
Tentativa de login falhou para o usu√°rio 'visitante'.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Tentativa de login falhou para o usu√°rio 'admin'.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Tentativa de login falhou para o usu√°rio 'admin'.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Tentativa de login falhou para o usu√°rio 'admin'.
Usu√°rio 'Victor' fez login.
Admin 'Victor' ADICIONOU o aluno 'admin'.
Admin 'Victor' CRIOU a conta de login para 'admin'.
Admin 'Victor' DELETOU o aluno 'admin'.
Admin 'Victor' DELETOU o usu√°rio associado a 'admin'.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Admin 'Victor' CRIOU a aula 'Aula 01'.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Admin 'Victor' DELETOU a aula 'Aula 01'.
Admin 'Victor' CRIOU a aula 'teste'.
Admin 'Victor' EDITOU o aluno 'Kleber'.
Admin 'Victor' ALTEROU a permiss√£o de 'Kleber'.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Admin 'Victor' EDITOU a aula 'teste'.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Admin 'Victor' CRIOU a aula 'Aula 01'.
Admin 'Victor' EDITOU a aula 'Aula 01'.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' EXPORTOU os dados para PDF.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Victor' fez login.
Usu√°rio 'Victor' EXPORTOU os dados para PDF.
Usu√°rio 'Victor' fez logout.
Usu√°rio 'Kleber' fez login.
Usu√°rio 'Kleber' EXPORTOU os dados para PDF.
Usu√°rio 'Kleber' fez logout.
Usu√°rio 'Aluno' fez login.
